spring:
  application:
    name: admin

spring-doc:
  packages-to-scan: com.parking.admin.adapter.in.web
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    display-query-params-without-oauth2: true
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

security:
  whitelist:
    /swagger-ui/**,
    /v3/api-docs/**,
    /swagger-ui.html,
    /swagger-ui/index.html,
    /api-docs/**

api:
  base-url: "http://localhost:8080"
  item-management:
    policy:
      get: "/api/vehicles/search"
      patch: "/api/parking-fees"